"""add5

Revision ID: 1b88bbdbe296
Revises: 8596e0611d0a
Create Date: 2026-02-18 20:50:44.794056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b88bbdbe296'
down_revision: Union[str, Sequence[str], None] = '8596e0611d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('orders_products_unique_id', 'orders_products', ['order_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_products_unique_id', 'orders_products', type_='unique')
    # ### end Alembic commands ###
